### ISSUE TITLE
Compute duplicate lines

### ISSUE THREAD

**Issue by saucisson** [juristique/penalyzer#1]
Or for better results, compute duplicate paragraphs.

**Comment by saucisson** [comment]
First results show:

``` yaml
$ penalyzer "../france.code-penal/Partie législative/" duplicates
---
duplicates:
  ratio: 0.20451055662188
  max: 64
  copied: 2131
  total: 10420
...
```

So, it seems that 20% of the text is copy/pasted from other parts. It is quite a lot, as the program only counts markdown lines that are exactly the same.
