### ISSUE TITLE
Compute dependencies between articles

### ISSUE THREAD

**Issue by saucisson** [juristique/penalyzer#2]

**Comment by saucisson** [comment]
``` yaml
$ penalyzer ../france.code-penal/Partie\ législative/ dependencies
---
dependencies:
  cycles:
  - - 224-4
    - 224-1
    - 224-2
  - - 461-2
    - 462-1
    - 461-16
  - - 461-2
    - 462-1
  - - 461-2
    - 462-1
    - 461-6
  max: 27
  average: 1.5394736842105
  depth: 6
  png: /tmp/lua_4V4pcM
...
```

![dependencies](https://cloud.githubusercontent.com/assets/1818862/17884936/2f264daa-691b-11e6-90dd-3840618ca2b4.png)
