### ISSUE TITLE
Compute sentences complexity

### ISSUE THREAD

**Issue by saucisson** [juristique/penalyzer#3]

**Comment by saucisson** [comment]
``` yaml
$ penalyzer ../france.code-penal/Partie\ législative/ sentences
---
sentences:
  above_all: 1373
  above: 1298
  average: 29.710080285459
  longest: 152
...
```

The threshold has been set to 30 words per sentence. Results mean that 1.300 sentences are above this threshold, that is also the average sentence length in the whole text.
The longest sentence has 152 words, which is far too much.
